//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace businesslogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOut_Collections
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkOut_Collections()
        {
            this.WorkOut_Actives = new HashSet<WorkOut_Actives>();
        }
    
        public string workout_title { get; set; }
        public string workout_note { get; set; }
        public Nullable<double> calories_burn_per_min { get; set; }
        public Nullable<int> category_id { get; set; }
        public int workout_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOut_Actives> WorkOut_Actives { get; set; }
        public virtual WorkOut_Categorys WorkOut_Categorys { get; set; }
    }
}
